// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: activity_queries.sql

package tabmate

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertActivityEvent = `-- name: InsertActivityEvent :one
INSERT INTO activity_events (
    event_type,
    actor_id,
    actor_name,
    entity_type,
    entity_code,
    entity_name,
    metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, event_type, actor_id, actor_name, entity_type, entity_code, entity_name, metadata, created_at
`

type InsertActivityEventParams struct {
	EventType  string      `json:"event_type"`
	ActorID    pgtype.UUID `json:"actor_id"`
	ActorName  string      `json:"actor_name"`
	EntityType string      `json:"entity_type"`
	EntityCode string      `json:"entity_code"`
	EntityName string      `json:"entity_name"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) InsertActivityEvent(ctx context.Context, arg InsertActivityEventParams) (ActivityEvents, error) {
	row := q.db.QueryRow(ctx, insertActivityEvent,
		arg.EventType,
		arg.ActorID,
		arg.ActorName,
		arg.EntityType,
		arg.EntityCode,
		arg.EntityName,
		arg.Metadata,
	)
	var i ActivityEvents
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.ActorID,
		&i.ActorName,
		&i.EntityType,
		&i.EntityCode,
		&i.EntityName,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listActivityEventsForUser = `-- name: ListActivityEventsForUser :many
SELECT e.id, e.event_type, e.actor_id, e.actor_name, e.entity_type, e.entity_code, e.entity_name, e.metadata, e.created_at
FROM activity_events e
WHERE e.entity_code IN (
    SELECT t.table_code
    FROM tables t
    JOIN table_members tm ON tm.table_id = t.id
    WHERE tm.user_id = $1
    UNION
    SELECT s.split_code
    FROM splits s
    JOIN split_members sm ON sm.split_id = s.id
    WHERE sm.user_id = $1
)
ORDER BY e.created_at DESC
LIMIT 50
`

// Returns the 50 most recent events from all tables and splits the user belongs to.
func (q *Queries) ListActivityEventsForUser(ctx context.Context, userID pgtype.UUID) ([]ActivityEvents, error) {
	rows, err := q.db.Query(ctx, listActivityEventsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityEvents{}
	for rows.Next() {
		var i ActivityEvents
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.ActorID,
			&i.ActorName,
			&i.EntityType,
			&i.EntityCode,
			&i.EntityName,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
