// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: fixedbills_queries.sql

package tabmate

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOpenFixedBills = `-- name: CountOpenFixedBills :one
SELECT COUNT(*) FROM fixedbills
WHERE status = 'open'
`

func (q *Queries) CountOpenFixedBills(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenFixedBills)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFixedBill = `-- name: CreateFixedBill :one
INSERT INTO fixedbills (created_by, bill_code, name, description, total_amount, status)
VALUES ($1, $2, $3, $4, $5, 'open')
RETURNING id, created_by, bill_code, name, description, total_amount, status, created_at, updated_at, settled_at
`

type CreateFixedBillParams struct {
	CreatedBy   pgtype.UUID    `json:"created_by"`
	BillCode    string         `json:"bill_code"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	TotalAmount pgtype.Numeric `json:"total_amount"`
}

func (q *Queries) CreateFixedBill(ctx context.Context, arg CreateFixedBillParams) (Fixedbills, error) {
	row := q.db.QueryRow(ctx, createFixedBill,
		arg.CreatedBy,
		arg.BillCode,
		arg.Name,
		arg.Description,
		arg.TotalAmount,
	)
	var i Fixedbills
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.BillCode,
		&i.Name,
		&i.Description,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
	)
	return i, err
}

const deleteFixedBillByCode = `-- name: DeleteFixedBillByCode :exec
DELETE FROM fixedbills
WHERE bill_code = $1
`

func (q *Queries) DeleteFixedBillByCode(ctx context.Context, billCode string) error {
	_, err := q.db.Exec(ctx, deleteFixedBillByCode, billCode)
	return err
}

const getFixedBillByCode = `-- name: GetFixedBillByCode :one
SELECT id, created_by, bill_code, name, description, total_amount, status, created_at, updated_at, settled_at FROM fixedbills
WHERE bill_code = $1
`

func (q *Queries) GetFixedBillByCode(ctx context.Context, billCode string) (Fixedbills, error) {
	row := q.db.QueryRow(ctx, getFixedBillByCode, billCode)
	var i Fixedbills
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.BillCode,
		&i.Name,
		&i.Description,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
	)
	return i, err
}

const getFixedBillByID = `-- name: GetFixedBillByID :one
SELECT id, created_by, bill_code, name, description, total_amount, status, created_at, updated_at, settled_at FROM fixedbills
WHERE id = $1
`

func (q *Queries) GetFixedBillByID(ctx context.Context, id pgtype.UUID) (Fixedbills, error) {
	row := q.db.QueryRow(ctx, getFixedBillByID, id)
	var i Fixedbills
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.BillCode,
		&i.Name,
		&i.Description,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
	)
	return i, err
}

const listFixedBillsByUserID = `-- name: ListFixedBillsByUserID :many
SELECT id, created_by, bill_code, name, description, total_amount, status, created_at, updated_at, settled_at FROM fixedbills
WHERE created_by = $1
ORDER BY created_at DESC
`

// Get all bills a user created
func (q *Queries) ListFixedBillsByUserID(ctx context.Context, createdBy pgtype.UUID) ([]Fixedbills, error) {
	rows, err := q.db.Query(ctx, listFixedBillsByUserID, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fixedbills{}
	for rows.Next() {
		var i Fixedbills
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.BillCode,
			&i.Name,
			&i.Description,
			&i.TotalAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFixedBillAmount = `-- name: UpdateFixedBillAmount :one
UPDATE fixedbills
SET total_amount = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, created_by, bill_code, name, description, total_amount, status, created_at, updated_at, settled_at
`

type UpdateFixedBillAmountParams struct {
	ID          pgtype.UUID    `json:"id"`
	TotalAmount pgtype.Numeric `json:"total_amount"`
}

func (q *Queries) UpdateFixedBillAmount(ctx context.Context, arg UpdateFixedBillAmountParams) (Fixedbills, error) {
	row := q.db.QueryRow(ctx, updateFixedBillAmount, arg.ID, arg.TotalAmount)
	var i Fixedbills
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.BillCode,
		&i.Name,
		&i.Description,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
	)
	return i, err
}

const updateFixedBillStatus = `-- name: UpdateFixedBillStatus :one
UPDATE fixedbills
SET 
    status = $2,
    settled_at = CASE WHEN $2 = 'settled' THEN NOW() ELSE settled_at END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, created_by, bill_code, name, description, total_amount, status, created_at, updated_at, settled_at
`

type UpdateFixedBillStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateFixedBillStatus(ctx context.Context, arg UpdateFixedBillStatusParams) (Fixedbills, error) {
	row := q.db.QueryRow(ctx, updateFixedBillStatus, arg.ID, arg.Status)
	var i Fixedbills
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.BillCode,
		&i.Name,
		&i.Description,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
	)
	return i, err
}
