// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package tabmate

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Items struct {
	ID                 pgtype.UUID        `json:"id"`
	TableCode          string             `json:"table_code"`
	AddedByUserID      pgtype.UUID        `json:"added_by_user_id"`
	Name               string             `json:"name"`
	Price              pgtype.Numeric     `json:"price"`
	Quantity           int32              `json:"quantity"`
	Description        pgtype.Text        `json:"description"`
	Source             pgtype.Text        `json:"source"`
	OriginalParsedText pgtype.Text        `json:"original_parsed_text"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type SplitMembers struct {
	SplitID    pgtype.UUID        `json:"split_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	AmountOwed pgtype.Numeric     `json:"amount_owed"`
	IsSettled  bool               `json:"is_settled"`
	SettledAt  pgtype.Timestamptz `json:"settled_at"`
	Role       string             `json:"role"`
	JoinedAt   pgtype.Timestamptz `json:"joined_at"`
}

type Splits struct {
	ID          pgtype.UUID        `json:"id"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	SplitCode   string             `json:"split_code"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	SettledAt   pgtype.Timestamptz `json:"settled_at"`
}

type TableMembers struct {
	TableID   pgtype.UUID        `json:"table_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
	Role      string             `json:"role"`
	IsSettled bool               `json:"is_settled"`
}

type Tables struct {
	ID             pgtype.UUID        `json:"id"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	TableCode      string             `json:"table_code"`
	Name           pgtype.Text        `json:"name"`
	RestaurantName pgtype.Text        `json:"restaurant_name"`
	Status         string             `json:"status"`
	MenuUrl        pgtype.Text        `json:"menu_url"`
	Vat            pgtype.Numeric     `json:"vat"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ClosedAt       pgtype.Timestamptz `json:"closed_at"`
	ScannedMenu    pgtype.Text        `json:"scanned_menu"`
}

type Users struct {
	ID                pgtype.UUID        `json:"id"`
	Name              pgtype.Text        `json:"name"`
	ProfilePictureUrl pgtype.Text        `json:"profile_picture_url"`
	CognitoSub        string             `json:"cognito_sub"`
	Email             string             `json:"email"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	PushToken         pgtype.Text        `json:"push_token"`
}
