// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package tabmate

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Items struct {
	ID                 pgtype.UUID        `json:"id"`
	TableCode          string             `json:"table_code"`
	AddedByUserID      pgtype.UUID        `json:"added_by_user_id"`
	Name               string             `json:"name"`
	Price              pgtype.Numeric     `json:"price"`
	Quantity           int32              `json:"quantity"`
	Description        pgtype.Text        `json:"description"`
	Source             pgtype.Text        `json:"source"`
	OriginalParsedText pgtype.Text        `json:"original_parsed_text"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type TableMembers struct {
	TableID   pgtype.UUID        `json:"table_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
	Role      string             `json:"role"`
	IsSettled bool               `json:"is_settled"`
}

type Tables struct {
	ID             pgtype.UUID        `json:"id"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	TableCode      string             `json:"table_code"`
	Name           pgtype.Text        `json:"name"`
	RestaurantName pgtype.Text        `json:"restaurant_name"`
	Status         string             `json:"status"`
	MenuUrl        pgtype.Text        `json:"menu_url"`
	Members        []int32            `json:"members"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ClosedAt       pgtype.Timestamptz `json:"closed_at"`
}

type Users struct {
	ID                pgtype.UUID        `json:"id"`
	Name              pgtype.Text        `json:"name"`
	ProfilePictureUrl pgtype.Text        `json:"profile_picture_url"`
	CognitoSub        string             `json:"cognito_sub"`
	Email             string             `json:"email"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
