// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package tablesclea

import (
	"context"
)

type Querier interface {
	CreateTable(ctx context.Context, arg CreateTableParams) (Tables, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	FindUser(ctx context.Context, email string) (Users, error)
	ListAllUsers(ctx context.Context) ([]Users, error)
}

var _ Querier = (*Queries)(nil)
