// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: split_items_queries.sql

package tabmate

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSplitItem = `-- name: AddSplitItem :one
INSERT INTO split_items (split_id, name, price, quantity, remaining_qty, added_by_user_id)
VALUES ($1, $2, $3, $4, $4, $5)
RETURNING id, split_id, name, price, quantity, remaining_qty, added_by_user_id, created_at
`

type AddSplitItemParams struct {
	SplitID       pgtype.UUID    `json:"split_id"`
	Name          string         `json:"name"`
	Price         pgtype.Numeric `json:"price"`
	Quantity      int32          `json:"quantity"`
	AddedByUserID pgtype.UUID    `json:"added_by_user_id"`
}

func (q *Queries) AddSplitItem(ctx context.Context, arg AddSplitItemParams) (SplitItems, error) {
	row := q.db.QueryRow(ctx, addSplitItem,
		arg.SplitID,
		arg.Name,
		arg.Price,
		arg.Quantity,
		arg.AddedByUserID,
	)
	var i SplitItems
	err := row.Scan(
		&i.ID,
		&i.SplitID,
		&i.Name,
		&i.Price,
		&i.Quantity,
		&i.RemainingQty,
		&i.AddedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const addSplitItemClaim = `-- name: AddSplitItemClaim :one
INSERT INTO split_item_claims (split_item_id, claimed_by_user_id, quantity_claimed)
VALUES ($1, $2, $3)
ON CONFLICT (split_item_id, claimed_by_user_id)
DO UPDATE SET quantity_claimed = EXCLUDED.quantity_claimed, claimed_at = NOW()
RETURNING split_item_id, claimed_by_user_id, quantity_claimed, claimed_at
`

type AddSplitItemClaimParams struct {
	SplitItemID     pgtype.UUID `json:"split_item_id"`
	ClaimedByUserID pgtype.UUID `json:"claimed_by_user_id"`
	QuantityClaimed int32       `json:"quantity_claimed"`
}

func (q *Queries) AddSplitItemClaim(ctx context.Context, arg AddSplitItemClaimParams) (SplitItemClaims, error) {
	row := q.db.QueryRow(ctx, addSplitItemClaim, arg.SplitItemID, arg.ClaimedByUserID, arg.QuantityClaimed)
	var i SplitItemClaims
	err := row.Scan(
		&i.SplitItemID,
		&i.ClaimedByUserID,
		&i.QuantityClaimed,
		&i.ClaimedAt,
	)
	return i, err
}

const countUnclaimedSplitItems = `-- name: CountUnclaimedSplitItems :one
SELECT COUNT(*) FROM split_items WHERE split_id = $1 AND remaining_qty > 0
`

func (q *Queries) CountUnclaimedSplitItems(ctx context.Context, splitID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnclaimedSplitItems, splitID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllSplitItems = `-- name: DeleteAllSplitItems :exec
DELETE FROM split_items WHERE split_id = $1
`

func (q *Queries) DeleteAllSplitItems(ctx context.Context, splitID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllSplitItems, splitID)
	return err
}

const deleteSplitItem = `-- name: DeleteSplitItem :exec
DELETE FROM split_items WHERE id = $1
`

func (q *Queries) DeleteSplitItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSplitItem, id)
	return err
}

const deleteSplitItemClaim = `-- name: DeleteSplitItemClaim :exec
DELETE FROM split_item_claims
WHERE split_item_id = $1 AND claimed_by_user_id = $2
`

type DeleteSplitItemClaimParams struct {
	SplitItemID     pgtype.UUID `json:"split_item_id"`
	ClaimedByUserID pgtype.UUID `json:"claimed_by_user_id"`
}

func (q *Queries) DeleteSplitItemClaim(ctx context.Context, arg DeleteSplitItemClaimParams) error {
	_, err := q.db.Exec(ctx, deleteSplitItemClaim, arg.SplitItemID, arg.ClaimedByUserID)
	return err
}

const getSplitItem = `-- name: GetSplitItem :one
SELECT id, split_id, name, price, quantity, remaining_qty, added_by_user_id, created_at FROM split_items WHERE id = $1
`

func (q *Queries) GetSplitItem(ctx context.Context, id pgtype.UUID) (SplitItems, error) {
	row := q.db.QueryRow(ctx, getSplitItem, id)
	var i SplitItems
	err := row.Scan(
		&i.ID,
		&i.SplitID,
		&i.Name,
		&i.Price,
		&i.Quantity,
		&i.RemainingQty,
		&i.AddedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getSplitItemClaim = `-- name: GetSplitItemClaim :one
SELECT split_item_id, claimed_by_user_id, quantity_claimed, claimed_at FROM split_item_claims
WHERE split_item_id = $1 AND claimed_by_user_id = $2
`

type GetSplitItemClaimParams struct {
	SplitItemID     pgtype.UUID `json:"split_item_id"`
	ClaimedByUserID pgtype.UUID `json:"claimed_by_user_id"`
}

func (q *Queries) GetSplitItemClaim(ctx context.Context, arg GetSplitItemClaimParams) (SplitItemClaims, error) {
	row := q.db.QueryRow(ctx, getSplitItemClaim, arg.SplitItemID, arg.ClaimedByUserID)
	var i SplitItemClaims
	err := row.Scan(
		&i.SplitItemID,
		&i.ClaimedByUserID,
		&i.QuantityClaimed,
		&i.ClaimedAt,
	)
	return i, err
}

const listClaimsForItem = `-- name: ListClaimsForItem :many
SELECT
    sic.split_item_id,
    sic.claimed_by_user_id,
    sic.quantity_claimed,
    sic.claimed_at,
    u.name AS user_name
FROM split_item_claims sic
JOIN users u ON sic.claimed_by_user_id = u.id
WHERE sic.split_item_id = $1
`

type ListClaimsForItemRow struct {
	SplitItemID     pgtype.UUID        `json:"split_item_id"`
	ClaimedByUserID pgtype.UUID        `json:"claimed_by_user_id"`
	QuantityClaimed int32              `json:"quantity_claimed"`
	ClaimedAt       pgtype.Timestamptz `json:"claimed_at"`
	UserName        pgtype.Text        `json:"user_name"`
}

func (q *Queries) ListClaimsForItem(ctx context.Context, splitItemID pgtype.UUID) ([]ListClaimsForItemRow, error) {
	rows, err := q.db.Query(ctx, listClaimsForItem, splitItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClaimsForItemRow{}
	for rows.Next() {
		var i ListClaimsForItemRow
		if err := rows.Scan(
			&i.SplitItemID,
			&i.ClaimedByUserID,
			&i.QuantityClaimed,
			&i.ClaimedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaimsForSplit = `-- name: ListClaimsForSplit :many
SELECT
    sic.split_item_id,
    sic.claimed_by_user_id,
    sic.quantity_claimed,
    sic.claimed_at,
    si.name  AS item_name,
    si.price AS item_price,
    u.name   AS user_name
FROM split_item_claims sic
JOIN split_items si ON sic.split_item_id = si.id
JOIN users u ON sic.claimed_by_user_id = u.id
WHERE si.split_id = $1
`

type ListClaimsForSplitRow struct {
	SplitItemID     pgtype.UUID        `json:"split_item_id"`
	ClaimedByUserID pgtype.UUID        `json:"claimed_by_user_id"`
	QuantityClaimed int32              `json:"quantity_claimed"`
	ClaimedAt       pgtype.Timestamptz `json:"claimed_at"`
	ItemName        string             `json:"item_name"`
	ItemPrice       pgtype.Numeric     `json:"item_price"`
	UserName        pgtype.Text        `json:"user_name"`
}

func (q *Queries) ListClaimsForSplit(ctx context.Context, splitID pgtype.UUID) ([]ListClaimsForSplitRow, error) {
	rows, err := q.db.Query(ctx, listClaimsForSplit, splitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClaimsForSplitRow{}
	for rows.Next() {
		var i ListClaimsForSplitRow
		if err := rows.Scan(
			&i.SplitItemID,
			&i.ClaimedByUserID,
			&i.QuantityClaimed,
			&i.ClaimedAt,
			&i.ItemName,
			&i.ItemPrice,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSplitItems = `-- name: ListSplitItems :many
SELECT id, split_id, name, price, quantity, remaining_qty, added_by_user_id, created_at FROM split_items WHERE split_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListSplitItems(ctx context.Context, splitID pgtype.UUID) ([]SplitItems, error) {
	rows, err := q.db.Query(ctx, listSplitItems, splitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SplitItems{}
	for rows.Next() {
		var i SplitItems
		if err := rows.Scan(
			&i.ID,
			&i.SplitID,
			&i.Name,
			&i.Price,
			&i.Quantity,
			&i.RemainingQty,
			&i.AddedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSplitItemRemainingQty = `-- name: UpdateSplitItemRemainingQty :one
UPDATE split_items SET remaining_qty = $2 WHERE id = $1 RETURNING id, split_id, name, price, quantity, remaining_qty, added_by_user_id, created_at
`

type UpdateSplitItemRemainingQtyParams struct {
	ID           pgtype.UUID `json:"id"`
	RemainingQty int32       `json:"remaining_qty"`
}

func (q *Queries) UpdateSplitItemRemainingQty(ctx context.Context, arg UpdateSplitItemRemainingQtyParams) (SplitItems, error) {
	row := q.db.QueryRow(ctx, updateSplitItemRemainingQty, arg.ID, arg.RemainingQty)
	var i SplitItems
	err := row.Scan(
		&i.ID,
		&i.SplitID,
		&i.Name,
		&i.Price,
		&i.Quantity,
		&i.RemainingQty,
		&i.AddedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const updateSplitReceiptDetails = `-- name: UpdateSplitReceiptDetails :one
UPDATE splits
SET
    tax_amount    = $2,
    tip_amount    = $3,
    tip_is_shared = $4,
    total_amount  = $5,
    split_type    = 'receipt',
    updated_at    = NOW()
WHERE id = $1
RETURNING id, created_by, split_code, name, description, total_amount, status, created_at, updated_at, settled_at, tax_amount, tip_amount, tip_is_shared, split_type
`

type UpdateSplitReceiptDetailsParams struct {
	ID          pgtype.UUID    `json:"id"`
	TaxAmount   pgtype.Numeric `json:"tax_amount"`
	TipAmount   pgtype.Numeric `json:"tip_amount"`
	TipIsShared bool           `json:"tip_is_shared"`
	TotalAmount pgtype.Numeric `json:"total_amount"`
}

func (q *Queries) UpdateSplitReceiptDetails(ctx context.Context, arg UpdateSplitReceiptDetailsParams) (Splits, error) {
	row := q.db.QueryRow(ctx, updateSplitReceiptDetails,
		arg.ID,
		arg.TaxAmount,
		arg.TipAmount,
		arg.TipIsShared,
		arg.TotalAmount,
	)
	var i Splits
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.SplitCode,
		&i.Name,
		&i.Description,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.TaxAmount,
		&i.TipAmount,
		&i.TipIsShared,
		&i.SplitType,
	)
	return i, err
}

const updateSplitTotalAmount = `-- name: UpdateSplitTotalAmount :one
UPDATE splits SET total_amount = $2, updated_at = NOW() WHERE id = $1 RETURNING id, created_by, split_code, name, description, total_amount, status, created_at, updated_at, settled_at, tax_amount, tip_amount, tip_is_shared, split_type
`

type UpdateSplitTotalAmountParams struct {
	ID          pgtype.UUID    `json:"id"`
	TotalAmount pgtype.Numeric `json:"total_amount"`
}

func (q *Queries) UpdateSplitTotalAmount(ctx context.Context, arg UpdateSplitTotalAmountParams) (Splits, error) {
	row := q.db.QueryRow(ctx, updateSplitTotalAmount, arg.ID, arg.TotalAmount)
	var i Splits
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.SplitCode,
		&i.Name,
		&i.Description,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.TaxAmount,
		&i.TipAmount,
		&i.TipIsShared,
		&i.SplitType,
	)
	return i, err
}
