// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: splits_queries.sql

package tabmate

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOpenSplits = `-- name: CountOpenSplits :one
SELECT COUNT(*) FROM splits WHERE status = 'open'
`

func (q *Queries) CountOpenSplits(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenSplits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSplit = `-- name: CreateSplit :one
INSERT INTO splits (created_by, split_code, name, description, total_amount, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_by, split_code, name, description, total_amount, status, created_at, updated_at, settled_at, tax_amount, tip_amount, tip_is_shared, split_type
`

type CreateSplitParams struct {
	CreatedBy   pgtype.UUID    `json:"created_by"`
	SplitCode   string         `json:"split_code"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	TotalAmount pgtype.Numeric `json:"total_amount"`
	Status      string         `json:"status"`
}

func (q *Queries) CreateSplit(ctx context.Context, arg CreateSplitParams) (Splits, error) {
	row := q.db.QueryRow(ctx, createSplit,
		arg.CreatedBy,
		arg.SplitCode,
		arg.Name,
		arg.Description,
		arg.TotalAmount,
		arg.Status,
	)
	var i Splits
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.SplitCode,
		&i.Name,
		&i.Description,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.TaxAmount,
		&i.TipAmount,
		&i.TipIsShared,
		&i.SplitType,
	)
	return i, err
}

const deleteSplitByCode = `-- name: DeleteSplitByCode :exec
DELETE FROM splits WHERE split_code = $1
`

func (q *Queries) DeleteSplitByCode(ctx context.Context, splitCode string) error {
	_, err := q.db.Exec(ctx, deleteSplitByCode, splitCode)
	return err
}

const getSplitByCode = `-- name: GetSplitByCode :one
SELECT id, created_by, split_code, name, description, total_amount, status, created_at, updated_at, settled_at, tax_amount, tip_amount, tip_is_shared, split_type FROM splits WHERE split_code = $1
`

func (q *Queries) GetSplitByCode(ctx context.Context, splitCode string) (Splits, error) {
	row := q.db.QueryRow(ctx, getSplitByCode, splitCode)
	var i Splits
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.SplitCode,
		&i.Name,
		&i.Description,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.TaxAmount,
		&i.TipAmount,
		&i.TipIsShared,
		&i.SplitType,
	)
	return i, err
}

const getSplitByID = `-- name: GetSplitByID :one
SELECT id, created_by, split_code, name, description, total_amount, status, created_at, updated_at, settled_at, tax_amount, tip_amount, tip_is_shared, split_type FROM splits WHERE id = $1
`

func (q *Queries) GetSplitByID(ctx context.Context, id pgtype.UUID) (Splits, error) {
	row := q.db.QueryRow(ctx, getSplitByID, id)
	var i Splits
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.SplitCode,
		&i.Name,
		&i.Description,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.TaxAmount,
		&i.TipAmount,
		&i.TipIsShared,
		&i.SplitType,
	)
	return i, err
}

const listSplitsByUserID = `-- name: ListSplitsByUserID :many
SELECT id, created_by, split_code, name, description, total_amount, status, created_at, updated_at, settled_at, tax_amount, tip_amount, tip_is_shared, split_type FROM splits WHERE created_by = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSplitsByUserID(ctx context.Context, createdBy pgtype.UUID) ([]Splits, error) {
	rows, err := q.db.Query(ctx, listSplitsByUserID, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Splits{}
	for rows.Next() {
		var i Splits
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.SplitCode,
			&i.Name,
			&i.Description,
			&i.TotalAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SettledAt,
			&i.TaxAmount,
			&i.TipAmount,
			&i.TipIsShared,
			&i.SplitType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSplitAmount = `-- name: UpdateSplitAmount :one
UPDATE splits SET total_amount = $2, updated_at = NOW() WHERE id = $1 RETURNING id, created_by, split_code, name, description, total_amount, status, created_at, updated_at, settled_at, tax_amount, tip_amount, tip_is_shared, split_type
`

type UpdateSplitAmountParams struct {
	ID          pgtype.UUID    `json:"id"`
	TotalAmount pgtype.Numeric `json:"total_amount"`
}

func (q *Queries) UpdateSplitAmount(ctx context.Context, arg UpdateSplitAmountParams) (Splits, error) {
	row := q.db.QueryRow(ctx, updateSplitAmount, arg.ID, arg.TotalAmount)
	var i Splits
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.SplitCode,
		&i.Name,
		&i.Description,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.TaxAmount,
		&i.TipAmount,
		&i.TipIsShared,
		&i.SplitType,
	)
	return i, err
}

const updateSplitStatus = `-- name: UpdateSplitStatus :one
UPDATE splits
SET
    status = $2,
    settled_at = CASE WHEN $2 = 'settled' THEN NOW() ELSE settled_at END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, created_by, split_code, name, description, total_amount, status, created_at, updated_at, settled_at, tax_amount, tip_amount, tip_is_shared, split_type
`

type UpdateSplitStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateSplitStatus(ctx context.Context, arg UpdateSplitStatusParams) (Splits, error) {
	row := q.db.QueryRow(ctx, updateSplitStatus, arg.ID, arg.Status)
	var i Splits
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.SplitCode,
		&i.Name,
		&i.Description,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.TaxAmount,
		&i.TipAmount,
		&i.TipIsShared,
		&i.SplitType,
	)
	return i, err
}
