// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: split_members_queries.sql

package tabmate

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserToSplit = `-- name: AddUserToSplit :one
INSERT INTO split_members (split_id, user_id, amount_owed, role)
VALUES ($1, $2, $3, $4)
RETURNING split_id, user_id, amount_owed, is_settled, settled_at, role, joined_at
`

type AddUserToSplitParams struct {
	SplitID    pgtype.UUID    `json:"split_id"`
	UserID     pgtype.UUID    `json:"user_id"`
	AmountOwed pgtype.Numeric `json:"amount_owed"`
	Role       string         `json:"role"`
}

func (q *Queries) AddUserToSplit(ctx context.Context, arg AddUserToSplitParams) (SplitMembers, error) {
	row := q.db.QueryRow(ctx, addUserToSplit,
		arg.SplitID,
		arg.UserID,
		arg.AmountOwed,
		arg.Role,
	)
	var i SplitMembers
	err := row.Scan(
		&i.SplitID,
		&i.UserID,
		&i.AmountOwed,
		&i.IsSettled,
		&i.SettledAt,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const countUnsettledSplitMembers = `-- name: CountUnsettledSplitMembers :one
SELECT COUNT(*) FROM split_members
WHERE split_id = $1 AND is_settled = FALSE
`

func (q *Queries) CountUnsettledSplitMembers(ctx context.Context, splitID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnsettledSplitMembers, splitID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSplitMember = `-- name: GetSplitMember :one
SELECT split_id, user_id, amount_owed, is_settled, settled_at, role, joined_at FROM split_members
WHERE split_id = $1 AND user_id = $2
`

type GetSplitMemberParams struct {
	SplitID pgtype.UUID `json:"split_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetSplitMember(ctx context.Context, arg GetSplitMemberParams) (SplitMembers, error) {
	row := q.db.QueryRow(ctx, getSplitMember, arg.SplitID, arg.UserID)
	var i SplitMembers
	err := row.Scan(
		&i.SplitID,
		&i.UserID,
		&i.AmountOwed,
		&i.IsSettled,
		&i.SettledAt,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const listSplitMembersBySplitID = `-- name: ListSplitMembersBySplitID :many
SELECT split_id, user_id, amount_owed, is_settled, settled_at, role, joined_at FROM split_members
WHERE split_id = $1
ORDER BY joined_at ASC
`

func (q *Queries) ListSplitMembersBySplitID(ctx context.Context, splitID pgtype.UUID) ([]SplitMembers, error) {
	rows, err := q.db.Query(ctx, listSplitMembersBySplitID, splitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SplitMembers{}
	for rows.Next() {
		var i SplitMembers
		if err := rows.Scan(
			&i.SplitID,
			&i.UserID,
			&i.AmountOwed,
			&i.IsSettled,
			&i.SettledAt,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSplitMembersWithUserDetails = `-- name: ListSplitMembersWithUserDetails :many
SELECT
    sm.split_id,
    sm.user_id,
    sm.amount_owed,
    sm.is_settled,
    sm.settled_at,
    sm.role,
    sm.joined_at,
    u.email AS user_email,
    u.name AS user_name,
    u.profile_picture_url AS user_profile_picture_url
FROM split_members sm
JOIN users u ON sm.user_id = u.id
WHERE sm.split_id = $1
ORDER BY sm.joined_at ASC
`

type ListSplitMembersWithUserDetailsRow struct {
	SplitID               pgtype.UUID        `json:"split_id"`
	UserID                pgtype.UUID        `json:"user_id"`
	AmountOwed            pgtype.Numeric     `json:"amount_owed"`
	IsSettled             bool               `json:"is_settled"`
	SettledAt             pgtype.Timestamptz `json:"settled_at"`
	Role                  string             `json:"role"`
	JoinedAt              pgtype.Timestamptz `json:"joined_at"`
	UserEmail             string             `json:"user_email"`
	UserName              pgtype.Text        `json:"user_name"`
	UserProfilePictureUrl pgtype.Text        `json:"user_profile_picture_url"`
}

// Get all members of a split with their user info
func (q *Queries) ListSplitMembersWithUserDetails(ctx context.Context, splitID pgtype.UUID) ([]ListSplitMembersWithUserDetailsRow, error) {
	rows, err := q.db.Query(ctx, listSplitMembersWithUserDetails, splitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSplitMembersWithUserDetailsRow{}
	for rows.Next() {
		var i ListSplitMembersWithUserDetailsRow
		if err := rows.Scan(
			&i.SplitID,
			&i.UserID,
			&i.AmountOwed,
			&i.IsSettled,
			&i.SettledAt,
			&i.Role,
			&i.JoinedAt,
			&i.UserEmail,
			&i.UserName,
			&i.UserProfilePictureUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSplitsForUser = `-- name: ListSplitsForUser :many
SELECT
    s.id AS split_id,
    s.split_code,
    s.name AS split_name,
    s.total_amount,
    s.status AS split_status,
    s.created_by AS split_creator,
    sm.role AS user_role_in_split,
    sm.amount_owed,
    sm.is_settled AS user_is_settled,
    sm.joined_at
FROM split_members sm
JOIN splits s ON sm.split_id = s.id
WHERE sm.user_id = $1
ORDER BY s.created_at DESC
`

type ListSplitsForUserRow struct {
	SplitID         pgtype.UUID        `json:"split_id"`
	SplitCode       string             `json:"split_code"`
	SplitName       string             `json:"split_name"`
	TotalAmount     pgtype.Numeric     `json:"total_amount"`
	SplitStatus     string             `json:"split_status"`
	SplitCreator    pgtype.UUID        `json:"split_creator"`
	UserRoleInSplit string             `json:"user_role_in_split"`
	AmountOwed      pgtype.Numeric     `json:"amount_owed"`
	UserIsSettled   bool               `json:"user_is_settled"`
	JoinedAt        pgtype.Timestamptz `json:"joined_at"`
}

// Get all splits a user is a member of
func (q *Queries) ListSplitsForUser(ctx context.Context, userID pgtype.UUID) ([]ListSplitsForUserRow, error) {
	rows, err := q.db.Query(ctx, listSplitsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSplitsForUserRow{}
	for rows.Next() {
		var i ListSplitsForUserRow
		if err := rows.Scan(
			&i.SplitID,
			&i.SplitCode,
			&i.SplitName,
			&i.TotalAmount,
			&i.SplitStatus,
			&i.SplitCreator,
			&i.UserRoleInSplit,
			&i.AmountOwed,
			&i.UserIsSettled,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recalculateSplitForAllMembers = `-- name: RecalculateSplitForAllMembers :exec
UPDATE split_members sm
SET amount_owed = (
    SELECT s.total_amount / COUNT(*)
    FROM split_members sm2
    WHERE sm2.split_id = sm.split_id
)
FROM splits s
WHERE sm.split_id = s.id AND sm.split_id = $1
`

// When someone joins/leaves, recalculate everyone's amount_owed
func (q *Queries) RecalculateSplitForAllMembers(ctx context.Context, splitID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, recalculateSplitForAllMembers, splitID)
	return err
}

const removeUserFromSplit = `-- name: RemoveUserFromSplit :exec
DELETE FROM split_members
WHERE split_id = $1 AND user_id = $2
`

type RemoveUserFromSplitParams struct {
	SplitID pgtype.UUID `json:"split_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveUserFromSplit(ctx context.Context, arg RemoveUserFromSplitParams) error {
	_, err := q.db.Exec(ctx, removeUserFromSplit, arg.SplitID, arg.UserID)
	return err
}

const updateSplitMemberSettledStatus = `-- name: UpdateSplitMemberSettledStatus :one
UPDATE split_members
SET
    is_settled = $3,
    settled_at = CASE WHEN $3 = TRUE THEN NOW() ELSE NULL END
WHERE split_id = $1 AND user_id = $2
RETURNING split_id, user_id, amount_owed, is_settled, settled_at, role, joined_at
`

type UpdateSplitMemberSettledStatusParams struct {
	SplitID   pgtype.UUID `json:"split_id"`
	UserID    pgtype.UUID `json:"user_id"`
	IsSettled bool        `json:"is_settled"`
}

func (q *Queries) UpdateSplitMemberSettledStatus(ctx context.Context, arg UpdateSplitMemberSettledStatusParams) (SplitMembers, error) {
	row := q.db.QueryRow(ctx, updateSplitMemberSettledStatus, arg.SplitID, arg.UserID, arg.IsSettled)
	var i SplitMembers
	err := row.Scan(
		&i.SplitID,
		&i.UserID,
		&i.AmountOwed,
		&i.IsSettled,
		&i.SettledAt,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
