// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: table_sync_operations_queries.sql

package tabmate

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const registerTableSyncOperation = `-- name: RegisterTableSyncOperation :execrows
INSERT INTO table_sync_operations (
    operation_id,
    table_code,
    user_id
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (operation_id) DO NOTHING
`

type RegisterTableSyncOperationParams struct {
	OperationID string      `json:"operation_id"`
	TableCode   string      `json:"table_code"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) RegisterTableSyncOperation(ctx context.Context, arg RegisterTableSyncOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, registerTableSyncOperation, arg.OperationID, arg.TableCode, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
