// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users_queries.sql

package tabmate

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkIfCognitoSubExists = `-- name: CheckIfCognitoSubExists :one
SELECT EXISTS (
    SELECT 1 FROM users
    WHERE email = $1
)
`

func (q *Queries) CheckIfCognitoSubExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, checkIfCognitoSubExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkIfEmailExists = `-- name: CheckIfEmailExists :one
SELECT EXISTS (
    SELECT 1 FROM users
    WHERE email = $1
)
`

func (q *Queries) CheckIfEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, checkIfEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, profile_picture_url, cognito_sub,  email)
VALUES ($1, $2, $3, $4)
RETURNING id, name, profile_picture_url, cognito_sub, email, created_at, updated_at, push_token, bank_name, account_name, account_number
`

type CreateUserParams struct {
	Name              pgtype.Text `json:"name"`
	ProfilePictureUrl pgtype.Text `json:"profile_picture_url"`
	CognitoSub        string      `json:"cognito_sub"`
	Email             string      `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Users, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.ProfilePictureUrl,
		arg.CognitoSub,
		arg.Email,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProfilePictureUrl,
		&i.CognitoSub,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushToken,
		&i.BankName,
		&i.AccountName,
		&i.AccountNumber,
	)
	return i, err
}

const deleteUserByCognitoSub = `-- name: DeleteUserByCognitoSub :exec
DELETE FROM users
WHERE cognito_sub = $1
`

func (q *Queries) DeleteUserByCognitoSub(ctx context.Context, cognitoSub string) error {
	_, err := q.db.Exec(ctx, deleteUserByCognitoSub, cognitoSub)
	return err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserByID, id)
	return err
}

const getUserByCognitoSub = `-- name: GetUserByCognitoSub :one
SELECT id, name, profile_picture_url, cognito_sub, email, created_at, updated_at, push_token, bank_name, account_name, account_number FROM users
WHERE cognito_sub = $1
`

func (q *Queries) GetUserByCognitoSub(ctx context.Context, cognitoSub string) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByCognitoSub, cognitoSub)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProfilePictureUrl,
		&i.CognitoSub,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushToken,
		&i.BankName,
		&i.AccountName,
		&i.AccountNumber,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, profile_picture_url, cognito_sub, email, created_at, updated_at, push_token, bank_name, account_name, account_number FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProfilePictureUrl,
		&i.CognitoSub,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushToken,
		&i.BankName,
		&i.AccountName,
		&i.AccountNumber,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, profile_picture_url, cognito_sub, email, created_at, updated_at, push_token, bank_name, account_name, account_number FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProfilePictureUrl,
		&i.CognitoSub,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushToken,
		&i.BankName,
		&i.AccountName,
		&i.AccountNumber,
	)
	return i, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, name, profile_picture_url, cognito_sub, email, created_at, updated_at, push_token, bank_name, account_name, account_number FROM users
`

func (q *Queries) ListAllUsers(ctx context.Context) ([]Users, error) {
	rows, err := q.db.Query(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Users{}
	for rows.Next() {
		var i Users
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProfilePictureUrl,
			&i.CognitoSub,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PushToken,
			&i.BankName,
			&i.AccountName,
			&i.AccountNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersByName = `-- name: SearchUsersByName :many
SELECT id, name, email, profile_picture_url FROM users
WHERE name ILIKE '%' || $1 || '%'
  AND id != $2
ORDER BY name ASC
LIMIT 10
`

type SearchUsersByNameParams struct {
	Column1 pgtype.Text `json:"column_1"`
	ID      pgtype.UUID `json:"id"`
}

type SearchUsersByNameRow struct {
	ID                pgtype.UUID `json:"id"`
	Name              pgtype.Text `json:"name"`
	Email             string      `json:"email"`
	ProfilePictureUrl pgtype.Text `json:"profile_picture_url"`
}

func (q *Queries) SearchUsersByName(ctx context.Context, arg SearchUsersByNameParams) ([]SearchUsersByNameRow, error) {
	rows, err := q.db.Query(ctx, searchUsersByName, arg.Column1, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersByNameRow{}
	for rows.Next() {
		var i SearchUsersByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.ProfilePictureUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users
SET
    email = $2,
    updated_at = NOW()
WHERE
    id = $1
RETURNING id, name, profile_picture_url, cognito_sub, email, created_at, updated_at, push_token, bank_name, account_name, account_number
`

type UpdateUserEmailParams struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (Users, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.ID, arg.Email)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProfilePictureUrl,
		&i.CognitoSub,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushToken,
		&i.BankName,
		&i.AccountName,
		&i.AccountNumber,
	)
	return i, err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users
SET
    name = $2,
    updated_at = NOW()
WHERE
    id = $1
RETURNING id, name, profile_picture_url, cognito_sub, email, created_at, updated_at, push_token, bank_name, account_name, account_number
`

type UpdateUserNameParams struct {
	ID   pgtype.UUID `json:"id"`
	Name pgtype.Text `json:"name"`
}

// Updates the name of a user given their ID and returns the updated user row.
func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (Users, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.ID, arg.Name)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProfilePictureUrl,
		&i.CognitoSub,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushToken,
		&i.BankName,
		&i.AccountName,
		&i.AccountNumber,
	)
	return i, err
}

const updateUserProfilePictureURL = `-- name: UpdateUserProfilePictureURL :one
UPDATE users
SET
    profile_picture_url = $2,
    updated_at = NOW()
WHERE
    id = $1
RETURNING id, name, profile_picture_url, cognito_sub, email, created_at, updated_at, push_token, bank_name, account_name, account_number
`

type UpdateUserProfilePictureURLParams struct {
	ID                pgtype.UUID `json:"id"`
	ProfilePictureUrl pgtype.Text `json:"profile_picture_url"`
}

func (q *Queries) UpdateUserProfilePictureURL(ctx context.Context, arg UpdateUserProfilePictureURLParams) (Users, error) {
	row := q.db.QueryRow(ctx, updateUserProfilePictureURL, arg.ID, arg.ProfilePictureUrl)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProfilePictureUrl,
		&i.CognitoSub,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushToken,
		&i.BankName,
		&i.AccountName,
		&i.AccountNumber,
	)
	return i, err
}

const updateUserPushToken = `-- name: UpdateUserPushToken :exec
UPDATE users
SET push_token = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateUserPushTokenParams struct {
	PushToken pgtype.Text `json:"push_token"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserPushToken(ctx context.Context, arg UpdateUserPushTokenParams) error {
	_, err := q.db.Exec(ctx, updateUserPushToken, arg.PushToken, arg.ID)
	return err
}

const updateBankDetails = `-- name: UpdateBankDetails :exec
UPDATE users
SET bank_name = $1, account_name = $2, account_number = $3, updated_at = NOW()
WHERE id = $4
`

type UpdateBankDetailsParams struct {
	BankName      pgtype.Text `json:"bank_name"`
	AccountName   pgtype.Text `json:"account_name"`
	AccountNumber pgtype.Text `json:"account_number"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateBankDetails(ctx context.Context, arg UpdateBankDetailsParams) error {
	_, err := q.db.Exec(ctx, updateBankDetails, arg.BankName, arg.AccountName, arg.AccountNumber, arg.ID)
	return err
}
